# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/robin/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/192.5728.100/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/robin/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/192.5728.100/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/robin/Master/SI3D/gkit2light

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/robin/Master/SI3D/gkit2light

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/robin/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/192.5728.100/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/robin/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/192.5728.100/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/robin/Master/SI3D/gkit2light/CMakeFiles /home/robin/Master/SI3D/gkit2light/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/robin/Master/SI3D/gkit2light/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named BezierSurface.exe

# Build rule for target.
BezierSurface.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BezierSurface.exe
.PHONY : BezierSurface.exe

# fast build rule for target.
BezierSurface.exe/fast:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/build
.PHONY : BezierSurface.exe/fast

#=============================================================================
# Target rules for targets named ComputeShaderTest.exe

# Build rule for target.
ComputeShaderTest.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ComputeShaderTest.exe
.PHONY : ComputeShaderTest.exe

# fast build rule for target.
ComputeShaderTest.exe/fast:
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/build
.PHONY : ComputeShaderTest.exe/fast

#=============================================================================
# Target rules for targets named shader_kit.exe

# Build rule for target.
shader_kit.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 shader_kit.exe
.PHONY : shader_kit.exe

# fast build rule for target.
shader_kit.exe/fast:
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/build
.PHONY : shader_kit.exe/fast

#=============================================================================
# Target rules for targets named imageViewer.exe

# Build rule for target.
imageViewer.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 imageViewer.exe
.PHONY : imageViewer.exe

# fast build rule for target.
imageViewer.exe/fast:
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/build
.PHONY : imageViewer.exe/fast

#=============================================================================
# Target rules for targets named RobotGL.exe

# Build rule for target.
RobotGL.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RobotGL.exe
.PHONY : RobotGL.exe

# fast build rule for target.
RobotGL.exe/fast:
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/build
.PHONY : RobotGL.exe/fast

#=============================================================================
# Target rules for targets named RayTraceCPU.exe

# Build rule for target.
RayTraceCPU.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RayTraceCPU.exe
.PHONY : RayTraceCPU.exe

# fast build rule for target.
RayTraceCPU.exe/fast:
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/build
.PHONY : RayTraceCPU.exe/fast

#=============================================================================
# Target rules for targets named TestOpenGL.exe

# Build rule for target.
TestOpenGL.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestOpenGL.exe
.PHONY : TestOpenGL.exe

# fast build rule for target.
TestOpenGL.exe/fast:
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/build
.PHONY : TestOpenGL.exe/fast

#=============================================================================
# Target rules for targets named RayTraceGPU.exe

# Build rule for target.
RayTraceGPU.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RayTraceGPU.exe
.PHONY : RayTraceGPU.exe

# fast build rule for target.
RayTraceGPU.exe/fast:
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/build
.PHONY : RayTraceGPU.exe/fast

src/RayTrace/CPU/RayTraceImageProcessing.o: src/RayTrace/CPU/RayTraceImageProcessing.cpp.o

.PHONY : src/RayTrace/CPU/RayTraceImageProcessing.o

# target to build an object file
src/RayTrace/CPU/RayTraceImageProcessing.cpp.o:
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/RayTrace/CPU/RayTraceImageProcessing.cpp.o
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/RayTrace/CPU/RayTraceImageProcessing.cpp.o
.PHONY : src/RayTrace/CPU/RayTraceImageProcessing.cpp.o

src/RayTrace/CPU/RayTraceImageProcessing.i: src/RayTrace/CPU/RayTraceImageProcessing.cpp.i

.PHONY : src/RayTrace/CPU/RayTraceImageProcessing.i

# target to preprocess a source file
src/RayTrace/CPU/RayTraceImageProcessing.cpp.i:
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/RayTrace/CPU/RayTraceImageProcessing.cpp.i
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/RayTrace/CPU/RayTraceImageProcessing.cpp.i
.PHONY : src/RayTrace/CPU/RayTraceImageProcessing.cpp.i

src/RayTrace/CPU/RayTraceImageProcessing.s: src/RayTrace/CPU/RayTraceImageProcessing.cpp.s

.PHONY : src/RayTrace/CPU/RayTraceImageProcessing.s

# target to generate assembly for a file
src/RayTrace/CPU/RayTraceImageProcessing.cpp.s:
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/RayTrace/CPU/RayTraceImageProcessing.cpp.s
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/RayTrace/CPU/RayTraceImageProcessing.cpp.s
.PHONY : src/RayTrace/CPU/RayTraceImageProcessing.cpp.s

src/RayTrace/CPU/mainCPU.o: src/RayTrace/CPU/mainCPU.cpp.o

.PHONY : src/RayTrace/CPU/mainCPU.o

# target to build an object file
src/RayTrace/CPU/mainCPU.cpp.o:
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/RayTrace/CPU/mainCPU.cpp.o
.PHONY : src/RayTrace/CPU/mainCPU.cpp.o

src/RayTrace/CPU/mainCPU.i: src/RayTrace/CPU/mainCPU.cpp.i

.PHONY : src/RayTrace/CPU/mainCPU.i

# target to preprocess a source file
src/RayTrace/CPU/mainCPU.cpp.i:
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/RayTrace/CPU/mainCPU.cpp.i
.PHONY : src/RayTrace/CPU/mainCPU.cpp.i

src/RayTrace/CPU/mainCPU.s: src/RayTrace/CPU/mainCPU.cpp.s

.PHONY : src/RayTrace/CPU/mainCPU.s

# target to generate assembly for a file
src/RayTrace/CPU/mainCPU.cpp.s:
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/RayTrace/CPU/mainCPU.cpp.s
.PHONY : src/RayTrace/CPU/mainCPU.cpp.s

src/RayTrace/GPU/ComputeShaderTest.o: src/RayTrace/GPU/ComputeShaderTest.cpp.o

.PHONY : src/RayTrace/GPU/ComputeShaderTest.o

# target to build an object file
src/RayTrace/GPU/ComputeShaderTest.cpp.o:
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/RayTrace/GPU/ComputeShaderTest.cpp.o
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/RayTrace/GPU/ComputeShaderTest.cpp.o
.PHONY : src/RayTrace/GPU/ComputeShaderTest.cpp.o

src/RayTrace/GPU/ComputeShaderTest.i: src/RayTrace/GPU/ComputeShaderTest.cpp.i

.PHONY : src/RayTrace/GPU/ComputeShaderTest.i

# target to preprocess a source file
src/RayTrace/GPU/ComputeShaderTest.cpp.i:
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/RayTrace/GPU/ComputeShaderTest.cpp.i
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/RayTrace/GPU/ComputeShaderTest.cpp.i
.PHONY : src/RayTrace/GPU/ComputeShaderTest.cpp.i

src/RayTrace/GPU/ComputeShaderTest.s: src/RayTrace/GPU/ComputeShaderTest.cpp.s

.PHONY : src/RayTrace/GPU/ComputeShaderTest.s

# target to generate assembly for a file
src/RayTrace/GPU/ComputeShaderTest.cpp.s:
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/RayTrace/GPU/ComputeShaderTest.cpp.s
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/RayTrace/GPU/ComputeShaderTest.cpp.s
.PHONY : src/RayTrace/GPU/ComputeShaderTest.cpp.s

src/RayTrace/GPU/mainGPU.o: src/RayTrace/GPU/mainGPU.cpp.o

.PHONY : src/RayTrace/GPU/mainGPU.o

# target to build an object file
src/RayTrace/GPU/mainGPU.cpp.o:
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/RayTrace/GPU/mainGPU.cpp.o
.PHONY : src/RayTrace/GPU/mainGPU.cpp.o

src/RayTrace/GPU/mainGPU.i: src/RayTrace/GPU/mainGPU.cpp.i

.PHONY : src/RayTrace/GPU/mainGPU.i

# target to preprocess a source file
src/RayTrace/GPU/mainGPU.cpp.i:
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/RayTrace/GPU/mainGPU.cpp.i
.PHONY : src/RayTrace/GPU/mainGPU.cpp.i

src/RayTrace/GPU/mainGPU.s: src/RayTrace/GPU/mainGPU.cpp.s

.PHONY : src/RayTrace/GPU/mainGPU.s

# target to generate assembly for a file
src/RayTrace/GPU/mainGPU.cpp.s:
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/RayTrace/GPU/mainGPU.cpp.s
.PHONY : src/RayTrace/GPU/mainGPU.cpp.s

src/RayTrace/Utils/Utils.o: src/RayTrace/Utils/Utils.cpp.o

.PHONY : src/RayTrace/Utils/Utils.o

# target to build an object file
src/RayTrace/Utils/Utils.cpp.o:
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/RayTrace/Utils/Utils.cpp.o
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/RayTrace/Utils/Utils.cpp.o
.PHONY : src/RayTrace/Utils/Utils.cpp.o

src/RayTrace/Utils/Utils.i: src/RayTrace/Utils/Utils.cpp.i

.PHONY : src/RayTrace/Utils/Utils.i

# target to preprocess a source file
src/RayTrace/Utils/Utils.cpp.i:
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/RayTrace/Utils/Utils.cpp.i
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/RayTrace/Utils/Utils.cpp.i
.PHONY : src/RayTrace/Utils/Utils.cpp.i

src/RayTrace/Utils/Utils.s: src/RayTrace/Utils/Utils.cpp.s

.PHONY : src/RayTrace/Utils/Utils.s

# target to generate assembly for a file
src/RayTrace/Utils/Utils.cpp.s:
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/RayTrace/Utils/Utils.cpp.s
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/RayTrace/Utils/Utils.cpp.s
.PHONY : src/RayTrace/Utils/Utils.cpp.s

src/RobotGL/robotGL.o: src/RobotGL/robotGL.cpp.o

.PHONY : src/RobotGL/robotGL.o

# target to build an object file
src/RobotGL/robotGL.cpp.o:
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/RobotGL/robotGL.cpp.o
.PHONY : src/RobotGL/robotGL.cpp.o

src/RobotGL/robotGL.i: src/RobotGL/robotGL.cpp.i

.PHONY : src/RobotGL/robotGL.i

# target to preprocess a source file
src/RobotGL/robotGL.cpp.i:
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/RobotGL/robotGL.cpp.i
.PHONY : src/RobotGL/robotGL.cpp.i

src/RobotGL/robotGL.s: src/RobotGL/robotGL.cpp.s

.PHONY : src/RobotGL/robotGL.s

# target to generate assembly for a file
src/RobotGL/robotGL.cpp.s:
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/RobotGL/robotGL.cpp.s
.PHONY : src/RobotGL/robotGL.cpp.s

src/SurfaceBezier/Modelisation_TP3.o: src/SurfaceBezier/Modelisation_TP3.cpp.o

.PHONY : src/SurfaceBezier/Modelisation_TP3.o

# target to build an object file
src/SurfaceBezier/Modelisation_TP3.cpp.o:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/SurfaceBezier/Modelisation_TP3.cpp.o
.PHONY : src/SurfaceBezier/Modelisation_TP3.cpp.o

src/SurfaceBezier/Modelisation_TP3.i: src/SurfaceBezier/Modelisation_TP3.cpp.i

.PHONY : src/SurfaceBezier/Modelisation_TP3.i

# target to preprocess a source file
src/SurfaceBezier/Modelisation_TP3.cpp.i:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/SurfaceBezier/Modelisation_TP3.cpp.i
.PHONY : src/SurfaceBezier/Modelisation_TP3.cpp.i

src/SurfaceBezier/Modelisation_TP3.s: src/SurfaceBezier/Modelisation_TP3.cpp.s

.PHONY : src/SurfaceBezier/Modelisation_TP3.s

# target to generate assembly for a file
src/SurfaceBezier/Modelisation_TP3.cpp.s:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/SurfaceBezier/Modelisation_TP3.cpp.s
.PHONY : src/SurfaceBezier/Modelisation_TP3.cpp.s

src/TestOpenGL.o: src/TestOpenGL.cpp.o

.PHONY : src/TestOpenGL.o

# target to build an object file
src/TestOpenGL.cpp.o:
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/TestOpenGL.cpp.o
.PHONY : src/TestOpenGL.cpp.o

src/TestOpenGL.i: src/TestOpenGL.cpp.i

.PHONY : src/TestOpenGL.i

# target to preprocess a source file
src/TestOpenGL.cpp.i:
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/TestOpenGL.cpp.i
.PHONY : src/TestOpenGL.cpp.i

src/TestOpenGL.s: src/TestOpenGL.cpp.s

.PHONY : src/TestOpenGL.s

# target to generate assembly for a file
src/TestOpenGL.cpp.s:
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/TestOpenGL.cpp.s
.PHONY : src/TestOpenGL.cpp.s

src/gKit/app.o: src/gKit/app.cpp.o

.PHONY : src/gKit/app.o

# target to build an object file
src/gKit/app.cpp.o:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/app.cpp.o
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/app.cpp.o
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/app.cpp.o
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/app.cpp.o
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/app.cpp.o
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/app.cpp.o
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/app.cpp.o
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/app.cpp.o
.PHONY : src/gKit/app.cpp.o

src/gKit/app.i: src/gKit/app.cpp.i

.PHONY : src/gKit/app.i

# target to preprocess a source file
src/gKit/app.cpp.i:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/app.cpp.i
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/app.cpp.i
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/app.cpp.i
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/app.cpp.i
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/app.cpp.i
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/app.cpp.i
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/app.cpp.i
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/app.cpp.i
.PHONY : src/gKit/app.cpp.i

src/gKit/app.s: src/gKit/app.cpp.s

.PHONY : src/gKit/app.s

# target to generate assembly for a file
src/gKit/app.cpp.s:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/app.cpp.s
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/app.cpp.s
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/app.cpp.s
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/app.cpp.s
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/app.cpp.s
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/app.cpp.s
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/app.cpp.s
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/app.cpp.s
.PHONY : src/gKit/app.cpp.s

src/gKit/app_camera.o: src/gKit/app_camera.cpp.o

.PHONY : src/gKit/app_camera.o

# target to build an object file
src/gKit/app_camera.cpp.o:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/app_camera.cpp.o
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/app_camera.cpp.o
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/app_camera.cpp.o
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/app_camera.cpp.o
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/app_camera.cpp.o
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/app_camera.cpp.o
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/app_camera.cpp.o
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/app_camera.cpp.o
.PHONY : src/gKit/app_camera.cpp.o

src/gKit/app_camera.i: src/gKit/app_camera.cpp.i

.PHONY : src/gKit/app_camera.i

# target to preprocess a source file
src/gKit/app_camera.cpp.i:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/app_camera.cpp.i
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/app_camera.cpp.i
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/app_camera.cpp.i
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/app_camera.cpp.i
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/app_camera.cpp.i
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/app_camera.cpp.i
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/app_camera.cpp.i
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/app_camera.cpp.i
.PHONY : src/gKit/app_camera.cpp.i

src/gKit/app_camera.s: src/gKit/app_camera.cpp.s

.PHONY : src/gKit/app_camera.s

# target to generate assembly for a file
src/gKit/app_camera.cpp.s:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/app_camera.cpp.s
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/app_camera.cpp.s
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/app_camera.cpp.s
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/app_camera.cpp.s
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/app_camera.cpp.s
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/app_camera.cpp.s
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/app_camera.cpp.s
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/app_camera.cpp.s
.PHONY : src/gKit/app_camera.cpp.s

src/gKit/app_time.o: src/gKit/app_time.cpp.o

.PHONY : src/gKit/app_time.o

# target to build an object file
src/gKit/app_time.cpp.o:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/app_time.cpp.o
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/app_time.cpp.o
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/app_time.cpp.o
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/app_time.cpp.o
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/app_time.cpp.o
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/app_time.cpp.o
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/app_time.cpp.o
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/app_time.cpp.o
.PHONY : src/gKit/app_time.cpp.o

src/gKit/app_time.i: src/gKit/app_time.cpp.i

.PHONY : src/gKit/app_time.i

# target to preprocess a source file
src/gKit/app_time.cpp.i:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/app_time.cpp.i
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/app_time.cpp.i
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/app_time.cpp.i
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/app_time.cpp.i
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/app_time.cpp.i
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/app_time.cpp.i
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/app_time.cpp.i
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/app_time.cpp.i
.PHONY : src/gKit/app_time.cpp.i

src/gKit/app_time.s: src/gKit/app_time.cpp.s

.PHONY : src/gKit/app_time.s

# target to generate assembly for a file
src/gKit/app_time.cpp.s:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/app_time.cpp.s
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/app_time.cpp.s
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/app_time.cpp.s
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/app_time.cpp.s
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/app_time.cpp.s
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/app_time.cpp.s
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/app_time.cpp.s
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/app_time.cpp.s
.PHONY : src/gKit/app_time.cpp.s

src/gKit/color.o: src/gKit/color.cpp.o

.PHONY : src/gKit/color.o

# target to build an object file
src/gKit/color.cpp.o:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/color.cpp.o
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/color.cpp.o
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/color.cpp.o
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/color.cpp.o
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/color.cpp.o
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/color.cpp.o
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/color.cpp.o
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/color.cpp.o
.PHONY : src/gKit/color.cpp.o

src/gKit/color.i: src/gKit/color.cpp.i

.PHONY : src/gKit/color.i

# target to preprocess a source file
src/gKit/color.cpp.i:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/color.cpp.i
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/color.cpp.i
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/color.cpp.i
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/color.cpp.i
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/color.cpp.i
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/color.cpp.i
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/color.cpp.i
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/color.cpp.i
.PHONY : src/gKit/color.cpp.i

src/gKit/color.s: src/gKit/color.cpp.s

.PHONY : src/gKit/color.s

# target to generate assembly for a file
src/gKit/color.cpp.s:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/color.cpp.s
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/color.cpp.s
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/color.cpp.s
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/color.cpp.s
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/color.cpp.s
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/color.cpp.s
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/color.cpp.s
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/color.cpp.s
.PHONY : src/gKit/color.cpp.s

src/gKit/draw.o: src/gKit/draw.cpp.o

.PHONY : src/gKit/draw.o

# target to build an object file
src/gKit/draw.cpp.o:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/draw.cpp.o
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/draw.cpp.o
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/draw.cpp.o
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/draw.cpp.o
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/draw.cpp.o
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/draw.cpp.o
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/draw.cpp.o
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/draw.cpp.o
.PHONY : src/gKit/draw.cpp.o

src/gKit/draw.i: src/gKit/draw.cpp.i

.PHONY : src/gKit/draw.i

# target to preprocess a source file
src/gKit/draw.cpp.i:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/draw.cpp.i
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/draw.cpp.i
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/draw.cpp.i
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/draw.cpp.i
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/draw.cpp.i
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/draw.cpp.i
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/draw.cpp.i
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/draw.cpp.i
.PHONY : src/gKit/draw.cpp.i

src/gKit/draw.s: src/gKit/draw.cpp.s

.PHONY : src/gKit/draw.s

# target to generate assembly for a file
src/gKit/draw.cpp.s:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/draw.cpp.s
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/draw.cpp.s
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/draw.cpp.s
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/draw.cpp.s
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/draw.cpp.s
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/draw.cpp.s
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/draw.cpp.s
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/draw.cpp.s
.PHONY : src/gKit/draw.cpp.s

src/gKit/gamepads.o: src/gKit/gamepads.cpp.o

.PHONY : src/gKit/gamepads.o

# target to build an object file
src/gKit/gamepads.cpp.o:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/gamepads.cpp.o
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/gamepads.cpp.o
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/gamepads.cpp.o
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/gamepads.cpp.o
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/gamepads.cpp.o
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/gamepads.cpp.o
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/gamepads.cpp.o
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/gamepads.cpp.o
.PHONY : src/gKit/gamepads.cpp.o

src/gKit/gamepads.i: src/gKit/gamepads.cpp.i

.PHONY : src/gKit/gamepads.i

# target to preprocess a source file
src/gKit/gamepads.cpp.i:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/gamepads.cpp.i
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/gamepads.cpp.i
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/gamepads.cpp.i
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/gamepads.cpp.i
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/gamepads.cpp.i
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/gamepads.cpp.i
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/gamepads.cpp.i
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/gamepads.cpp.i
.PHONY : src/gKit/gamepads.cpp.i

src/gKit/gamepads.s: src/gKit/gamepads.cpp.s

.PHONY : src/gKit/gamepads.s

# target to generate assembly for a file
src/gKit/gamepads.cpp.s:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/gamepads.cpp.s
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/gamepads.cpp.s
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/gamepads.cpp.s
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/gamepads.cpp.s
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/gamepads.cpp.s
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/gamepads.cpp.s
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/gamepads.cpp.s
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/gamepads.cpp.s
.PHONY : src/gKit/gamepads.cpp.s

src/gKit/image.o: src/gKit/image.cpp.o

.PHONY : src/gKit/image.o

# target to build an object file
src/gKit/image.cpp.o:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/image.cpp.o
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/image.cpp.o
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/image.cpp.o
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/image.cpp.o
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/image.cpp.o
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/image.cpp.o
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/image.cpp.o
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/image.cpp.o
.PHONY : src/gKit/image.cpp.o

src/gKit/image.i: src/gKit/image.cpp.i

.PHONY : src/gKit/image.i

# target to preprocess a source file
src/gKit/image.cpp.i:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/image.cpp.i
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/image.cpp.i
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/image.cpp.i
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/image.cpp.i
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/image.cpp.i
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/image.cpp.i
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/image.cpp.i
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/image.cpp.i
.PHONY : src/gKit/image.cpp.i

src/gKit/image.s: src/gKit/image.cpp.s

.PHONY : src/gKit/image.s

# target to generate assembly for a file
src/gKit/image.cpp.s:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/image.cpp.s
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/image.cpp.s
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/image.cpp.s
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/image.cpp.s
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/image.cpp.s
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/image.cpp.s
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/image.cpp.s
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/image.cpp.s
.PHONY : src/gKit/image.cpp.s

src/gKit/image_hdr.o: src/gKit/image_hdr.cpp.o

.PHONY : src/gKit/image_hdr.o

# target to build an object file
src/gKit/image_hdr.cpp.o:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/image_hdr.cpp.o
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/image_hdr.cpp.o
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/image_hdr.cpp.o
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/image_hdr.cpp.o
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/image_hdr.cpp.o
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/image_hdr.cpp.o
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/image_hdr.cpp.o
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/image_hdr.cpp.o
.PHONY : src/gKit/image_hdr.cpp.o

src/gKit/image_hdr.i: src/gKit/image_hdr.cpp.i

.PHONY : src/gKit/image_hdr.i

# target to preprocess a source file
src/gKit/image_hdr.cpp.i:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/image_hdr.cpp.i
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/image_hdr.cpp.i
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/image_hdr.cpp.i
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/image_hdr.cpp.i
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/image_hdr.cpp.i
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/image_hdr.cpp.i
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/image_hdr.cpp.i
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/image_hdr.cpp.i
.PHONY : src/gKit/image_hdr.cpp.i

src/gKit/image_hdr.s: src/gKit/image_hdr.cpp.s

.PHONY : src/gKit/image_hdr.s

# target to generate assembly for a file
src/gKit/image_hdr.cpp.s:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/image_hdr.cpp.s
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/image_hdr.cpp.s
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/image_hdr.cpp.s
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/image_hdr.cpp.s
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/image_hdr.cpp.s
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/image_hdr.cpp.s
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/image_hdr.cpp.s
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/image_hdr.cpp.s
.PHONY : src/gKit/image_hdr.cpp.s

src/gKit/image_io.o: src/gKit/image_io.cpp.o

.PHONY : src/gKit/image_io.o

# target to build an object file
src/gKit/image_io.cpp.o:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/image_io.cpp.o
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/image_io.cpp.o
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/image_io.cpp.o
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/image_io.cpp.o
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/image_io.cpp.o
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/image_io.cpp.o
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/image_io.cpp.o
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/image_io.cpp.o
.PHONY : src/gKit/image_io.cpp.o

src/gKit/image_io.i: src/gKit/image_io.cpp.i

.PHONY : src/gKit/image_io.i

# target to preprocess a source file
src/gKit/image_io.cpp.i:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/image_io.cpp.i
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/image_io.cpp.i
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/image_io.cpp.i
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/image_io.cpp.i
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/image_io.cpp.i
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/image_io.cpp.i
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/image_io.cpp.i
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/image_io.cpp.i
.PHONY : src/gKit/image_io.cpp.i

src/gKit/image_io.s: src/gKit/image_io.cpp.s

.PHONY : src/gKit/image_io.s

# target to generate assembly for a file
src/gKit/image_io.cpp.s:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/image_io.cpp.s
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/image_io.cpp.s
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/image_io.cpp.s
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/image_io.cpp.s
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/image_io.cpp.s
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/image_io.cpp.s
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/image_io.cpp.s
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/image_io.cpp.s
.PHONY : src/gKit/image_io.cpp.s

src/gKit/mat.o: src/gKit/mat.cpp.o

.PHONY : src/gKit/mat.o

# target to build an object file
src/gKit/mat.cpp.o:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/mat.cpp.o
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/mat.cpp.o
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/mat.cpp.o
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/mat.cpp.o
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/mat.cpp.o
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/mat.cpp.o
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/mat.cpp.o
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/mat.cpp.o
.PHONY : src/gKit/mat.cpp.o

src/gKit/mat.i: src/gKit/mat.cpp.i

.PHONY : src/gKit/mat.i

# target to preprocess a source file
src/gKit/mat.cpp.i:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/mat.cpp.i
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/mat.cpp.i
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/mat.cpp.i
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/mat.cpp.i
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/mat.cpp.i
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/mat.cpp.i
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/mat.cpp.i
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/mat.cpp.i
.PHONY : src/gKit/mat.cpp.i

src/gKit/mat.s: src/gKit/mat.cpp.s

.PHONY : src/gKit/mat.s

# target to generate assembly for a file
src/gKit/mat.cpp.s:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/mat.cpp.s
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/mat.cpp.s
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/mat.cpp.s
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/mat.cpp.s
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/mat.cpp.s
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/mat.cpp.s
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/mat.cpp.s
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/mat.cpp.s
.PHONY : src/gKit/mat.cpp.s

src/gKit/mesh.o: src/gKit/mesh.cpp.o

.PHONY : src/gKit/mesh.o

# target to build an object file
src/gKit/mesh.cpp.o:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/mesh.cpp.o
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/mesh.cpp.o
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/mesh.cpp.o
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/mesh.cpp.o
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/mesh.cpp.o
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/mesh.cpp.o
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/mesh.cpp.o
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/mesh.cpp.o
.PHONY : src/gKit/mesh.cpp.o

src/gKit/mesh.i: src/gKit/mesh.cpp.i

.PHONY : src/gKit/mesh.i

# target to preprocess a source file
src/gKit/mesh.cpp.i:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/mesh.cpp.i
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/mesh.cpp.i
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/mesh.cpp.i
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/mesh.cpp.i
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/mesh.cpp.i
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/mesh.cpp.i
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/mesh.cpp.i
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/mesh.cpp.i
.PHONY : src/gKit/mesh.cpp.i

src/gKit/mesh.s: src/gKit/mesh.cpp.s

.PHONY : src/gKit/mesh.s

# target to generate assembly for a file
src/gKit/mesh.cpp.s:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/mesh.cpp.s
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/mesh.cpp.s
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/mesh.cpp.s
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/mesh.cpp.s
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/mesh.cpp.s
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/mesh.cpp.s
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/mesh.cpp.s
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/mesh.cpp.s
.PHONY : src/gKit/mesh.cpp.s

src/gKit/orbiter.o: src/gKit/orbiter.cpp.o

.PHONY : src/gKit/orbiter.o

# target to build an object file
src/gKit/orbiter.cpp.o:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/orbiter.cpp.o
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/orbiter.cpp.o
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/orbiter.cpp.o
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/orbiter.cpp.o
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/orbiter.cpp.o
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/orbiter.cpp.o
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/orbiter.cpp.o
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/orbiter.cpp.o
.PHONY : src/gKit/orbiter.cpp.o

src/gKit/orbiter.i: src/gKit/orbiter.cpp.i

.PHONY : src/gKit/orbiter.i

# target to preprocess a source file
src/gKit/orbiter.cpp.i:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/orbiter.cpp.i
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/orbiter.cpp.i
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/orbiter.cpp.i
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/orbiter.cpp.i
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/orbiter.cpp.i
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/orbiter.cpp.i
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/orbiter.cpp.i
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/orbiter.cpp.i
.PHONY : src/gKit/orbiter.cpp.i

src/gKit/orbiter.s: src/gKit/orbiter.cpp.s

.PHONY : src/gKit/orbiter.s

# target to generate assembly for a file
src/gKit/orbiter.cpp.s:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/orbiter.cpp.s
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/orbiter.cpp.s
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/orbiter.cpp.s
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/orbiter.cpp.s
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/orbiter.cpp.s
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/orbiter.cpp.s
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/orbiter.cpp.s
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/orbiter.cpp.s
.PHONY : src/gKit/orbiter.cpp.s

src/gKit/program.o: src/gKit/program.cpp.o

.PHONY : src/gKit/program.o

# target to build an object file
src/gKit/program.cpp.o:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/program.cpp.o
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/program.cpp.o
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/program.cpp.o
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/program.cpp.o
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/program.cpp.o
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/program.cpp.o
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/program.cpp.o
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/program.cpp.o
.PHONY : src/gKit/program.cpp.o

src/gKit/program.i: src/gKit/program.cpp.i

.PHONY : src/gKit/program.i

# target to preprocess a source file
src/gKit/program.cpp.i:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/program.cpp.i
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/program.cpp.i
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/program.cpp.i
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/program.cpp.i
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/program.cpp.i
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/program.cpp.i
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/program.cpp.i
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/program.cpp.i
.PHONY : src/gKit/program.cpp.i

src/gKit/program.s: src/gKit/program.cpp.s

.PHONY : src/gKit/program.s

# target to generate assembly for a file
src/gKit/program.cpp.s:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/program.cpp.s
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/program.cpp.s
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/program.cpp.s
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/program.cpp.s
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/program.cpp.s
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/program.cpp.s
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/program.cpp.s
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/program.cpp.s
.PHONY : src/gKit/program.cpp.s

src/gKit/rgbe.o: src/gKit/rgbe.cpp.o

.PHONY : src/gKit/rgbe.o

# target to build an object file
src/gKit/rgbe.cpp.o:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/rgbe.cpp.o
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/rgbe.cpp.o
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/rgbe.cpp.o
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/rgbe.cpp.o
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/rgbe.cpp.o
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/rgbe.cpp.o
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/rgbe.cpp.o
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/rgbe.cpp.o
.PHONY : src/gKit/rgbe.cpp.o

src/gKit/rgbe.i: src/gKit/rgbe.cpp.i

.PHONY : src/gKit/rgbe.i

# target to preprocess a source file
src/gKit/rgbe.cpp.i:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/rgbe.cpp.i
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/rgbe.cpp.i
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/rgbe.cpp.i
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/rgbe.cpp.i
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/rgbe.cpp.i
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/rgbe.cpp.i
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/rgbe.cpp.i
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/rgbe.cpp.i
.PHONY : src/gKit/rgbe.cpp.i

src/gKit/rgbe.s: src/gKit/rgbe.cpp.s

.PHONY : src/gKit/rgbe.s

# target to generate assembly for a file
src/gKit/rgbe.cpp.s:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/rgbe.cpp.s
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/rgbe.cpp.s
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/rgbe.cpp.s
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/rgbe.cpp.s
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/rgbe.cpp.s
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/rgbe.cpp.s
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/rgbe.cpp.s
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/rgbe.cpp.s
.PHONY : src/gKit/rgbe.cpp.s

src/gKit/text.o: src/gKit/text.cpp.o

.PHONY : src/gKit/text.o

# target to build an object file
src/gKit/text.cpp.o:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/text.cpp.o
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/text.cpp.o
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/text.cpp.o
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/text.cpp.o
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/text.cpp.o
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/text.cpp.o
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/text.cpp.o
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/text.cpp.o
.PHONY : src/gKit/text.cpp.o

src/gKit/text.i: src/gKit/text.cpp.i

.PHONY : src/gKit/text.i

# target to preprocess a source file
src/gKit/text.cpp.i:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/text.cpp.i
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/text.cpp.i
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/text.cpp.i
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/text.cpp.i
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/text.cpp.i
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/text.cpp.i
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/text.cpp.i
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/text.cpp.i
.PHONY : src/gKit/text.cpp.i

src/gKit/text.s: src/gKit/text.cpp.s

.PHONY : src/gKit/text.s

# target to generate assembly for a file
src/gKit/text.cpp.s:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/text.cpp.s
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/text.cpp.s
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/text.cpp.s
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/text.cpp.s
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/text.cpp.s
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/text.cpp.s
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/text.cpp.s
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/text.cpp.s
.PHONY : src/gKit/text.cpp.s

src/gKit/texture.o: src/gKit/texture.cpp.o

.PHONY : src/gKit/texture.o

# target to build an object file
src/gKit/texture.cpp.o:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/texture.cpp.o
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/texture.cpp.o
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/texture.cpp.o
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/texture.cpp.o
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/texture.cpp.o
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/texture.cpp.o
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/texture.cpp.o
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/texture.cpp.o
.PHONY : src/gKit/texture.cpp.o

src/gKit/texture.i: src/gKit/texture.cpp.i

.PHONY : src/gKit/texture.i

# target to preprocess a source file
src/gKit/texture.cpp.i:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/texture.cpp.i
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/texture.cpp.i
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/texture.cpp.i
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/texture.cpp.i
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/texture.cpp.i
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/texture.cpp.i
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/texture.cpp.i
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/texture.cpp.i
.PHONY : src/gKit/texture.cpp.i

src/gKit/texture.s: src/gKit/texture.cpp.s

.PHONY : src/gKit/texture.s

# target to generate assembly for a file
src/gKit/texture.cpp.s:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/texture.cpp.s
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/texture.cpp.s
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/texture.cpp.s
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/texture.cpp.s
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/texture.cpp.s
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/texture.cpp.s
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/texture.cpp.s
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/texture.cpp.s
.PHONY : src/gKit/texture.cpp.s

src/gKit/uniforms.o: src/gKit/uniforms.cpp.o

.PHONY : src/gKit/uniforms.o

# target to build an object file
src/gKit/uniforms.cpp.o:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/uniforms.cpp.o
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/uniforms.cpp.o
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/uniforms.cpp.o
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/uniforms.cpp.o
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/uniforms.cpp.o
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/uniforms.cpp.o
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/uniforms.cpp.o
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/uniforms.cpp.o
.PHONY : src/gKit/uniforms.cpp.o

src/gKit/uniforms.i: src/gKit/uniforms.cpp.i

.PHONY : src/gKit/uniforms.i

# target to preprocess a source file
src/gKit/uniforms.cpp.i:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/uniforms.cpp.i
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/uniforms.cpp.i
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/uniforms.cpp.i
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/uniforms.cpp.i
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/uniforms.cpp.i
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/uniforms.cpp.i
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/uniforms.cpp.i
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/uniforms.cpp.i
.PHONY : src/gKit/uniforms.cpp.i

src/gKit/uniforms.s: src/gKit/uniforms.cpp.s

.PHONY : src/gKit/uniforms.s

# target to generate assembly for a file
src/gKit/uniforms.cpp.s:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/uniforms.cpp.s
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/uniforms.cpp.s
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/uniforms.cpp.s
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/uniforms.cpp.s
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/uniforms.cpp.s
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/uniforms.cpp.s
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/uniforms.cpp.s
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/uniforms.cpp.s
.PHONY : src/gKit/uniforms.cpp.s

src/gKit/vec.o: src/gKit/vec.cpp.o

.PHONY : src/gKit/vec.o

# target to build an object file
src/gKit/vec.cpp.o:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/vec.cpp.o
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/vec.cpp.o
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/vec.cpp.o
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/vec.cpp.o
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/vec.cpp.o
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/vec.cpp.o
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/vec.cpp.o
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/vec.cpp.o
.PHONY : src/gKit/vec.cpp.o

src/gKit/vec.i: src/gKit/vec.cpp.i

.PHONY : src/gKit/vec.i

# target to preprocess a source file
src/gKit/vec.cpp.i:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/vec.cpp.i
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/vec.cpp.i
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/vec.cpp.i
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/vec.cpp.i
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/vec.cpp.i
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/vec.cpp.i
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/vec.cpp.i
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/vec.cpp.i
.PHONY : src/gKit/vec.cpp.i

src/gKit/vec.s: src/gKit/vec.cpp.s

.PHONY : src/gKit/vec.s

# target to generate assembly for a file
src/gKit/vec.cpp.s:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/vec.cpp.s
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/vec.cpp.s
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/vec.cpp.s
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/vec.cpp.s
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/vec.cpp.s
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/vec.cpp.s
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/vec.cpp.s
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/vec.cpp.s
.PHONY : src/gKit/vec.cpp.s

src/gKit/wavefront.o: src/gKit/wavefront.cpp.o

.PHONY : src/gKit/wavefront.o

# target to build an object file
src/gKit/wavefront.cpp.o:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/wavefront.cpp.o
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/wavefront.cpp.o
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/wavefront.cpp.o
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/wavefront.cpp.o
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/wavefront.cpp.o
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/wavefront.cpp.o
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/wavefront.cpp.o
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/wavefront.cpp.o
.PHONY : src/gKit/wavefront.cpp.o

src/gKit/wavefront.i: src/gKit/wavefront.cpp.i

.PHONY : src/gKit/wavefront.i

# target to preprocess a source file
src/gKit/wavefront.cpp.i:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/wavefront.cpp.i
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/wavefront.cpp.i
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/wavefront.cpp.i
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/wavefront.cpp.i
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/wavefront.cpp.i
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/wavefront.cpp.i
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/wavefront.cpp.i
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/wavefront.cpp.i
.PHONY : src/gKit/wavefront.cpp.i

src/gKit/wavefront.s: src/gKit/wavefront.cpp.s

.PHONY : src/gKit/wavefront.s

# target to generate assembly for a file
src/gKit/wavefront.cpp.s:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/wavefront.cpp.s
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/wavefront.cpp.s
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/wavefront.cpp.s
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/wavefront.cpp.s
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/wavefront.cpp.s
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/wavefront.cpp.s
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/wavefront.cpp.s
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/wavefront.cpp.s
.PHONY : src/gKit/wavefront.cpp.s

src/gKit/widgets.o: src/gKit/widgets.cpp.o

.PHONY : src/gKit/widgets.o

# target to build an object file
src/gKit/widgets.cpp.o:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/widgets.cpp.o
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/widgets.cpp.o
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/widgets.cpp.o
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/widgets.cpp.o
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/widgets.cpp.o
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/widgets.cpp.o
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/widgets.cpp.o
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/widgets.cpp.o
.PHONY : src/gKit/widgets.cpp.o

src/gKit/widgets.i: src/gKit/widgets.cpp.i

.PHONY : src/gKit/widgets.i

# target to preprocess a source file
src/gKit/widgets.cpp.i:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/widgets.cpp.i
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/widgets.cpp.i
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/widgets.cpp.i
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/widgets.cpp.i
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/widgets.cpp.i
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/widgets.cpp.i
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/widgets.cpp.i
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/widgets.cpp.i
.PHONY : src/gKit/widgets.cpp.i

src/gKit/widgets.s: src/gKit/widgets.cpp.s

.PHONY : src/gKit/widgets.s

# target to generate assembly for a file
src/gKit/widgets.cpp.s:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/widgets.cpp.s
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/widgets.cpp.s
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/widgets.cpp.s
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/widgets.cpp.s
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/widgets.cpp.s
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/widgets.cpp.s
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/widgets.cpp.s
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/widgets.cpp.s
.PHONY : src/gKit/widgets.cpp.s

src/gKit/window.o: src/gKit/window.cpp.o

.PHONY : src/gKit/window.o

# target to build an object file
src/gKit/window.cpp.o:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/window.cpp.o
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/window.cpp.o
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/window.cpp.o
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/window.cpp.o
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/window.cpp.o
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/window.cpp.o
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/window.cpp.o
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/window.cpp.o
.PHONY : src/gKit/window.cpp.o

src/gKit/window.i: src/gKit/window.cpp.i

.PHONY : src/gKit/window.i

# target to preprocess a source file
src/gKit/window.cpp.i:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/window.cpp.i
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/window.cpp.i
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/window.cpp.i
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/window.cpp.i
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/window.cpp.i
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/window.cpp.i
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/window.cpp.i
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/window.cpp.i
.PHONY : src/gKit/window.cpp.i

src/gKit/window.s: src/gKit/window.cpp.s

.PHONY : src/gKit/window.s

# target to generate assembly for a file
src/gKit/window.cpp.s:
	$(MAKE) -f CMakeFiles/BezierSurface.exe.dir/build.make CMakeFiles/BezierSurface.exe.dir/src/gKit/window.cpp.s
	$(MAKE) -f CMakeFiles/ComputeShaderTest.exe.dir/build.make CMakeFiles/ComputeShaderTest.exe.dir/src/gKit/window.cpp.s
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/gKit/window.cpp.s
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/gKit/window.cpp.s
	$(MAKE) -f CMakeFiles/RobotGL.exe.dir/build.make CMakeFiles/RobotGL.exe.dir/src/gKit/window.cpp.s
	$(MAKE) -f CMakeFiles/RayTraceCPU.exe.dir/build.make CMakeFiles/RayTraceCPU.exe.dir/src/gKit/window.cpp.s
	$(MAKE) -f CMakeFiles/TestOpenGL.exe.dir/build.make CMakeFiles/TestOpenGL.exe.dir/src/gKit/window.cpp.s
	$(MAKE) -f CMakeFiles/RayTraceGPU.exe.dir/build.make CMakeFiles/RayTraceGPU.exe.dir/src/gKit/window.cpp.s
.PHONY : src/gKit/window.cpp.s

src/image_viewer.o: src/image_viewer.cpp.o

.PHONY : src/image_viewer.o

# target to build an object file
src/image_viewer.cpp.o:
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/image_viewer.cpp.o
.PHONY : src/image_viewer.cpp.o

src/image_viewer.i: src/image_viewer.cpp.i

.PHONY : src/image_viewer.i

# target to preprocess a source file
src/image_viewer.cpp.i:
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/image_viewer.cpp.i
.PHONY : src/image_viewer.cpp.i

src/image_viewer.s: src/image_viewer.cpp.s

.PHONY : src/image_viewer.s

# target to generate assembly for a file
src/image_viewer.cpp.s:
	$(MAKE) -f CMakeFiles/imageViewer.exe.dir/build.make CMakeFiles/imageViewer.exe.dir/src/image_viewer.cpp.s
.PHONY : src/image_viewer.cpp.s

src/shader_kit.o: src/shader_kit.cpp.o

.PHONY : src/shader_kit.o

# target to build an object file
src/shader_kit.cpp.o:
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/shader_kit.cpp.o
.PHONY : src/shader_kit.cpp.o

src/shader_kit.i: src/shader_kit.cpp.i

.PHONY : src/shader_kit.i

# target to preprocess a source file
src/shader_kit.cpp.i:
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/shader_kit.cpp.i
.PHONY : src/shader_kit.cpp.i

src/shader_kit.s: src/shader_kit.cpp.s

.PHONY : src/shader_kit.s

# target to generate assembly for a file
src/shader_kit.cpp.s:
	$(MAKE) -f CMakeFiles/shader_kit.exe.dir/build.make CMakeFiles/shader_kit.exe.dir/src/shader_kit.cpp.s
.PHONY : src/shader_kit.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... BezierSurface.exe"
	@echo "... ComputeShaderTest.exe"
	@echo "... shader_kit.exe"
	@echo "... imageViewer.exe"
	@echo "... RobotGL.exe"
	@echo "... RayTraceCPU.exe"
	@echo "... TestOpenGL.exe"
	@echo "... RayTraceGPU.exe"
	@echo "... src/RayTrace/CPU/RayTraceImageProcessing.o"
	@echo "... src/RayTrace/CPU/RayTraceImageProcessing.i"
	@echo "... src/RayTrace/CPU/RayTraceImageProcessing.s"
	@echo "... src/RayTrace/CPU/mainCPU.o"
	@echo "... src/RayTrace/CPU/mainCPU.i"
	@echo "... src/RayTrace/CPU/mainCPU.s"
	@echo "... src/RayTrace/GPU/ComputeShaderTest.o"
	@echo "... src/RayTrace/GPU/ComputeShaderTest.i"
	@echo "... src/RayTrace/GPU/ComputeShaderTest.s"
	@echo "... src/RayTrace/GPU/mainGPU.o"
	@echo "... src/RayTrace/GPU/mainGPU.i"
	@echo "... src/RayTrace/GPU/mainGPU.s"
	@echo "... src/RayTrace/Utils/Utils.o"
	@echo "... src/RayTrace/Utils/Utils.i"
	@echo "... src/RayTrace/Utils/Utils.s"
	@echo "... src/RobotGL/robotGL.o"
	@echo "... src/RobotGL/robotGL.i"
	@echo "... src/RobotGL/robotGL.s"
	@echo "... src/SurfaceBezier/Modelisation_TP3.o"
	@echo "... src/SurfaceBezier/Modelisation_TP3.i"
	@echo "... src/SurfaceBezier/Modelisation_TP3.s"
	@echo "... src/TestOpenGL.o"
	@echo "... src/TestOpenGL.i"
	@echo "... src/TestOpenGL.s"
	@echo "... src/gKit/app.o"
	@echo "... src/gKit/app.i"
	@echo "... src/gKit/app.s"
	@echo "... src/gKit/app_camera.o"
	@echo "... src/gKit/app_camera.i"
	@echo "... src/gKit/app_camera.s"
	@echo "... src/gKit/app_time.o"
	@echo "... src/gKit/app_time.i"
	@echo "... src/gKit/app_time.s"
	@echo "... src/gKit/color.o"
	@echo "... src/gKit/color.i"
	@echo "... src/gKit/color.s"
	@echo "... src/gKit/draw.o"
	@echo "... src/gKit/draw.i"
	@echo "... src/gKit/draw.s"
	@echo "... src/gKit/gamepads.o"
	@echo "... src/gKit/gamepads.i"
	@echo "... src/gKit/gamepads.s"
	@echo "... src/gKit/image.o"
	@echo "... src/gKit/image.i"
	@echo "... src/gKit/image.s"
	@echo "... src/gKit/image_hdr.o"
	@echo "... src/gKit/image_hdr.i"
	@echo "... src/gKit/image_hdr.s"
	@echo "... src/gKit/image_io.o"
	@echo "... src/gKit/image_io.i"
	@echo "... src/gKit/image_io.s"
	@echo "... src/gKit/mat.o"
	@echo "... src/gKit/mat.i"
	@echo "... src/gKit/mat.s"
	@echo "... src/gKit/mesh.o"
	@echo "... src/gKit/mesh.i"
	@echo "... src/gKit/mesh.s"
	@echo "... src/gKit/orbiter.o"
	@echo "... src/gKit/orbiter.i"
	@echo "... src/gKit/orbiter.s"
	@echo "... src/gKit/program.o"
	@echo "... src/gKit/program.i"
	@echo "... src/gKit/program.s"
	@echo "... src/gKit/rgbe.o"
	@echo "... src/gKit/rgbe.i"
	@echo "... src/gKit/rgbe.s"
	@echo "... src/gKit/text.o"
	@echo "... src/gKit/text.i"
	@echo "... src/gKit/text.s"
	@echo "... src/gKit/texture.o"
	@echo "... src/gKit/texture.i"
	@echo "... src/gKit/texture.s"
	@echo "... src/gKit/uniforms.o"
	@echo "... src/gKit/uniforms.i"
	@echo "... src/gKit/uniforms.s"
	@echo "... src/gKit/vec.o"
	@echo "... src/gKit/vec.i"
	@echo "... src/gKit/vec.s"
	@echo "... src/gKit/wavefront.o"
	@echo "... src/gKit/wavefront.i"
	@echo "... src/gKit/wavefront.s"
	@echo "... src/gKit/widgets.o"
	@echo "... src/gKit/widgets.i"
	@echo "... src/gKit/widgets.s"
	@echo "... src/gKit/window.o"
	@echo "... src/gKit/window.i"
	@echo "... src/gKit/window.s"
	@echo "... src/image_viewer.o"
	@echo "... src/image_viewer.i"
	@echo "... src/image_viewer.s"
	@echo "... src/shader_kit.o"
	@echo "... src/shader_kit.i"
	@echo "... src/shader_kit.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

