set(CMAKE_BINARY_DIR "CMakeGeneratedFiles")
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY lib)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY lib)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY bin)

set(PERSONAL_COMPILE_FLAGS "-fopenmp")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${PERSONAL_COMPILE_FLAGS}")
set(CMAKE_CXX_STANDARD 14)
set(PROJECT_SOURCE_DIR "src")